# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('partnr', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
